# Generated by Django 4.2.6 on 2023-11-05 20:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('fathername', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('grade', models.IntegerField(validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(1)])),
                ('phone_number', models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)])),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
