# Generated by Django 5.0.6 on 2024-05-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessondetails',
            name='status',
            field=models.IntegerField(default=3),
        ),
    ]
