# Generated by Django 5.0.6 on 2024-05-13 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_lessondetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessondetails',
            name='homework',
            field=models.TextField(default='нет', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='lessondetails',
            name='notes',
            field=models.TextField(default='нет', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='lessondetails',
            name='topic',
            field=models.TextField(default='нет', max_length=100, null=True),
        ),
    ]
