# Generated by Django 5.0.6 on 2024-05-13 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_lessondetails_homework_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.DateTimeField(),
        ),
    ]
