# Generated by Django 4.2.6 on 2023-11-27 15:41

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='gender',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='worker',
            name='subject',
            field=models.ManyToManyField(to='catalog.subject'),
        ),
        migrations.CreateModel(
            name='Student_subjecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.subject')),
            ],
        ),
    ]
