# Generated by Django 4.2.6 on 2023-11-27 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_worker_gender_alter_worker_subject_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student_subjecs',
            name='subject',
        ),
        migrations.AddField(
            model_name='student_subjecs',
            name='subjects',
            field=models.ManyToManyField(to='catalog.subject'),
        ),
    ]
