# Generated by Django 5.0.6 on 2024-05-14 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_lessondetails_status_lessonstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessonstatus',
            name='status',
            field=models.IntegerField(default=3, null=True),
        ),
    ]
