# Generated by Django 5.0.6 on 2024-05-15 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_studentsattendance_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsattendance',
            name='student',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.student'),
        ),
    ]
