# Generated by Django 5.0.6 on 2024-05-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_studentsattendance_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentsattendance',
            old_name='student',
            new_name='students',
        ),
    ]
