# Generated by Django 5.0.4 on 2024-04-18 20:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='student',
            name='fathername',
            field=models.CharField(max_length=20, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='student',
            name='firstname',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='student',
            name='grade',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(11), django.core.validators.MinValueValidator(1)], verbose_name='Класс'),
        ),
        migrations.AlterField(
            model_name='student',
            name='lastname',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='student_subjects',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.student', verbose_name='Ученик'),
        ),
        migrations.AlterField(
            model_name='student_subjects',
            name='subjects',
            field=models.ManyToManyField(blank=True, null=True, to='catalog.subject', verbose_name='Дисциплины'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='date_of_birth',
            field=models.DateField(verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='fathername',
            field=models.CharField(max_length=20, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='firstname',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='gender',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='Пол'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='lastname',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.MinLengthValidator(11)], verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='subject',
            field=models.ManyToManyField(to='catalog.subject', verbose_name='Дисциплины'),
        ),
        migrations.CreateModel(
            name='Group_type_of_math_exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('ОГЭ', 'ОГЭ'), ('ЕГЭ', 'ЕГЭ')], default='ОГЭ', max_length=3, verbose_name='Тип экзамена')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.student', verbose_name='Группа')),
            ],
        ),
    ]
