# Generated by Django 5.0.6 on 2024-05-16 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_rename_student_studentsattendance_students'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessonDetails',
            new_name='LessonInfo',
        ),
    ]
