# Generated by Django 5.0.6 on 2024-05-16 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_rename_lessondetails_lessoninfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoninfo',
            name='homework',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='lessoninfo',
            name='notes',
            field=models.TextField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='lessoninfo',
            name='topic',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='LessonCancel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.IntegerField(default=3, null=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.lesson')),
            ],
        ),
    ]
