# Generated by Django 5.0.4 on 2024-04-18 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_alter_student_date_of_birth_alter_student_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_type_of_math_exam',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.group', verbose_name='Группа'),
        ),
    ]
