# Generated by Django 5.0.4 on 2024-05-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_group_type_of_math_exam_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='student',
        ),
        migrations.AlterField(
            model_name='group_type_of_math_exam',
            name='type',
            field=models.CharField(choices=[('Базовый', 'Базовый'), ('Профильный', 'Профильный')], max_length=11, verbose_name='Тип экзамена'),
        ),
    ]
