# Generated by Django 5.0.6 on 2024-05-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_lessoninfo_homework_alter_lessoninfo_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessoncancel',
            name='reason',
            field=models.TextField(null=True),
        ),
    ]
