# Generated by Django 5.0.4 on 2024-10-05 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0013_alter_lessoncancel_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessoninfo',
            name='materials',
            field=models.URLField(blank=True, null=True),
        ),
    ]
