# Generated by Django 5.0.4 on 2024-05-03 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_students_in_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='group_capacity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(1)]),
        ),
    ]
