# Generated by Django 5.0.4 on 2024-05-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0016_alter_group_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='created',
            field=models.BooleanField(default=False),
        ),
    ]
