# Generated by Django 5.0.6 on 2024-05-10 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_group_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student_subjects',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_subjects', to='catalog.student', verbose_name='Ученик'),
        ),
    ]
