# Generated by Django 5.0.6 on 2024-05-10 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_alter_student_subjects_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.DateTimeField()),
                ('duration', models.IntegerField(choices=[(1, '1 час'), (2, '2 часа')])),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.group')),
            ],
        ),
    ]
