# Generated by Django 5.0.6 on 2024-05-12 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0022_lessondetails_lessonstatus_studentsattendance_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_type_of_math_exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Базовый', 'Базовый'), ('Профильный', 'Профильный')], max_length=11, verbose_name='Тип экзамена')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.group', verbose_name='Группа')),
            ],
        ),
    ]
